### ISSUE TITLE
my bad records broke your service

### ISSUE THREAD

**Issue by meau** [RockefellerArchiveCenter/DACSspace#13]
I just wanted to give you a heads-up about an error that you may not have encountered before
`Traceback (most recent call last):
  File "single_level.py", line 155, in <module>
    main()
  File "single_level.py", line 153, in main
    spreadsheet.close()
AttributeError: 'str' object has no attribute 'close'`
I can give you the more complete response if that's useful.

Thanks for creating such a rad tool!

**Comment by helrond** [comment]
Thanks @meau! I think that line (which closes the csv file) may not actually be necessary: http://stackoverflow.com/questions/33642876/str-object-has-no-attribute-close

@a-berish would you be able to take a look at this?

**Comment by meau** [comment]
Tested -- it works! Thanks for the update, @a-berish !
