### ISSUE TITLE
Add linter and syntax formatter

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/DACSspace#18]
Add automated linting and syntax formatting. There are patterns for this in other RAC-developed apps:
- autopep8
- flake8
- isort
- implemented as a `git` pre-commit hook

**Comment by a-berish** [comment]
Example in RAC apps:
[nebula/.pre-commit-config.yaml](https://github.com/RockefellerArchiveCenter/nebula/blob/d9b9c14b7a7165a43e2ddeddc1cba35541c57898/.pre-commit-config.yaml)

> Pre-commit hooks are tests that run each time you attempt to commit. If the tests pass, the commit will be made, otherwise not.
[Pre-commit hooks](https://lorenzwalthert.github.io/precommit/)
