### ISSUE TITLE
Create validation class

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/DACSspace#23]
As part of #21, create a class which handles validating objects received from ArchivesSpace. This should be able to handle fairly abstract validation of data.

**Comment by helrond** [comment]
One potential validation method would be using JSONSchema. We'd need to evaluate whether or not creating those schema would be too much of a barrier for potential users. We'd also need to look at the kinds of validation we're looking to do and see if this approach would be overkill/not meet our use cases.

**Comment by a-berish** [comment]
fixed with PR #38
