### ISSUE TITLE
Build out note section in single-level required schema

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/DACSspace#44]
Currently, the notes section of the [single_level_required.json](https://github.com/RockefellerArchiveCenter/DACSspace/blob/base/single_level_required.json) is a placeholder.

We need to build out the schema to check for the scope and contents and conditions governing access notes.

See PR #40 for additional information.

**Comment by bonniegee** [comment]
I'm continuing to look into this, but wanted to note what is NOT working so far. Here's the relevant portion of the schema that I've tried to use `anyOf` with:
```
"notes": {
            "type": "array",
            "minItems": 2,
            "items": {
                "anyOf": [
                    {
                        "type": "object",
                        "required": ["type"],
                        "properties": {
                            "type": {
                                "type": "string",
                                "const": "accessrestrict"
                            }
                        }
                    }
                      ]
                }
```

I ran it against our valid fixture in https://jsonschemalint.com/#!/version/draft-07/markup/json , and the notes that are not required (but we can have anyway) caused validation to fail:
<img width="688" alt="Screen Shot 2022-03-23 at 18 10 43" src="https://user-images.githubusercontent.com/8737364/159804479-8b4f0b21-734d-44b1-b653-a3dce7d82b61.png">

**Comment by bonniegee** [comment]
Figured it out. Instead of using `items`, we need to use `contains`. So something like:

```
"notes": {
            "type": "array",
            "minItems": 2,
            "contains": {
                "type": "object",
                "required": [
                    "type"
                ],
                "properties": {
                    "type": {
                        "type": "string",
                        "const": "accessrestrict"
                    }
                }
            },
            "contains": {
                "type": "object",
                "required": [
                    "type"
                ],
                "properties": {
                    "type": {
                        "type": "string",
                        "const": "scopecontent"
                    }
                }
            }
        }
```

Though we will likely want to include a bit more, so may want to use subschemas for these notes.
