### ISSUE TITLE
Check metadata rights field in valid_resource.json

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/DACSspace#45]
The metadata rights field in the valid_resource.json is a placeholder since RAC addresses metadata rights outside of ArchivesSpace. We should make sure we go back to this and add something more substantial, or make sure this is enough to pass as valid json.

See [Line 152](https://github.com/RockefellerArchiveCenter/DACSspace/blob/66fa463c02a44fd28267b30d396e8a47fe4bd144/fixtures/valid_resource.json#L152)

**Comment by helrond** [comment]
It looks like this is expected to be an array of objects, so I think we can take a similar approach as we did with dates and other things that are lists of objects.
