### ISSUE TITLE
Address filename conventions/extension

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/DACSspace#46]
@daremiyo discovered that troublesome filenames (filenames with spaces and no extensions provided) will pass tests. We might want to consider building out a solution to this:

- Enhance the TestReporter class to include testing for specific filenames/characters/extensions
- Have the code fudge a troublesome filename into a better filename (remove spaces, add extension)
- Remove the option to include a filename. Instead, always use the same filename and always save the file in the same location with a standard filename or a filename based on the timestamp.

For additional information, see @daremiyo comment on PR #39 

> One thing to note for us to consider is how we should handle filename conventions for the file to which the results are being written. Do we want to specify a file extension like .csv; specify what characters shouldn’t be included like spaces, etc.

**Comment by helrond** [comment]
I think I might have misspoken when we talked about this today. Regardless of what we do, we'll want our unit tests (i.e. the TestReporter class) to cover the logic that we write to handle filenames. 

In terms of what we do, I think there are three avenues, all of which have their upsides and downsides:
1. check the filename that's passed in and throw an error if it doesn't have an extension or contains any illegal characters. This is probably the safest option but could be frustrating for users if we don't have good error messages.
2. check the filename that's passed in and add an extension or replace any illegal characters as necessary. The downside to this is that the output file could end up being named different from what someone expects.
3. provide a default filename. The downside to this is that it would be hard to know what the output filename is without having knowledge of DACSspace internals, so it would be hard to do something programmatically with the output (like send it in an email)

There might be other solutions though!

**Comment by helrond** [comment]
Implement #1, make sure that error is thrown early enough in the process.
