### ISSUE TITLE
Rethink handling of AS configs

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/DACSspace#62]
**Is your feature request related to a problem? Please describe.**
The current implementation of this library asks for a config file with ArchivesSpace credentials. This works with a standalone script, but not with an installable package.

**Describe the solution you'd like**
Rethink how we provide AS configs to DACSspace. A couple of (non-mutually-exclusive) options:
- Allow users to point to a config file (if we're going to do this we should consider whether it makes sense to just move all the configs to a file
- Add additional arguments for AS credentials
- Look at how ASnake handles configuration and see if there's an approach we can piggyback on there.

**Comment by bonniegee** [comment]
Quick thought on the second proposed solution--this would also mean that users would expose their passwords in the command prompt, which could be annoying for things like posting screenshots when troubleshooting, or setting up a cron job with a non-generic ASpace user.

**Comment by helrond** [comment]
Documenting some additional thoughts while I'm thinking about it:
- One challenge with putting everything in a config file is that it is likely that users will want to trigger runs using different schemas and or different values for `invalid_only` or `published_only`, which means that they'd then have to create a config file for each of those different approaches.
- I'm going to do some more research on recommended best practices for providing sensitive data to command line functions.

**Comment by helrond** [comment]
[this article](https://smallstep.com/blog/command-line-secrets/) is a good overview and it seems to me like a config file might be the best balance of simplicity and security for us.
