### ISSUE TITLE
TypeError when running dacsspace

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/DACSspace#80]
**Describe the bug**
When running dacsspace I get this error:
`TypeError: _StoreAction.__init__() got an unexpected keyword argument 'typ'`

**To Reproduce**
1. `dacsspace test.csv`
4. See error `TypeError: _StoreAction.__init__() got an unexpected keyword argument 'typ'`

**Expected behavior**
The script to run :)

**Additional context**
Found this [article](https://stackoverflow.com/questions/33574270/typeerror-init-got-an-unexpected-keyword-argument-type-in-argparse), seems like it's argparse messing things up?

**Comment by a-berish** [comment]
Typo in [line 17](https://github.com/RockefellerArchiveCenter/DACSspace/blob/5edc66932c21b5d718e0ffa90d7347e11de04784/dacsspace/command_line.py#L17) of `command_line.py`

**Comment by a-berish** [comment]
Addressed the typo in branch [issue-80](https://github.com/RockefellerArchiveCenter/DACSspace/tree/issue-80) but still getting this error:

`Amys-Air:DACSspace aberish$ dacsspace test.csv
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/dacsspace", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dacsspace/command_line.py", line 14, in main
    parser.add_argument(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 1422, in add_argument
    action = action_class(**kwargs)
TypeError: _StoreAction.__init__() got an unexpected keyword argument 'typ'`

I made sure I was on the correct branch before trying to run it again locally, but the error remains the same reference `typ` which has been fixed. Another thing I am questioning is why the error is referencing line 8 in dacsspace

@helrond any thoughts on this?

**Comment by helrond** [comment]
@a-berish after updating that typo locally, you'll need to reinstall dacsspace, otherwise you're just executing the previous (broken) build. From the root of the repo, `pip install .`
